export type ReportRow = Record<string, unknown>;

function escapeCsv(value: unknown) {
  const text = value == null ? '' : String(value);
  return `"${text.replace(/"/g, '""')}"`;
}

export function downloadExcel(filename: string, rows: ReportRow[]) {
  if (!rows.length) return;

  const headers = Object.keys(rows[0]);
  const table = `
    <table>
      <thead>
        <tr>${headers.map((h) => `<th>${escapeHtml(h)}</th>`).join('')}</tr>
      </thead>
      <tbody>
        ${rows
          .map(
            (row) =>
              `<tr>${headers.map((h) => `<td>${escapeHtml(row[h])}</td>`).join('')}</tr>`,
          )
          .join('')}
      </tbody>
    </table>
  `;

  const html = `<!doctype html>
<html>
<head>
<meta charset="utf-8">
</head>
<body>
${table}
</body>
</html>`;

  const blob = new Blob([`\ufeff${html}`], {
    type: 'application/vnd.ms-excel;charset=utf-8',
  });

  triggerDownload(blob, `${filename}.xls`);
}

export function downloadCsv(filename: string, rows: ReportRow[]) {
  if (!rows.length) return;

  const headers = Object.keys(rows[0]);
  const csv = [
    headers.map(escapeCsv).join(','),
    ...rows.map((row) =>
      headers.map((h) => escapeCsv(row[h])).join(','),
    ),
  ].join('\r\n');

  triggerDownload(
    new Blob([`\ufeff${csv}`], {
      type: 'text/csv;charset=utf-8',
    }),
    `${filename}.csv`,
  );
}

export function printReport(
  title: string,
  rows: ReportRow[],
  meta: Record<string, string> = {},
) {
  const headers = rows.length ? Object.keys(rows[0]) : [];

  const metaHtml = Object.entries(meta)
    .map(
      ([key, value]) =>
        `<span><strong>${escapeHtml(key)}:</strong> ${escapeHtml(value)}</span>`,
    )
    .join('');

  const table = headers.length
    ? `<table>
        <thead>
          <tr>${headers.map((h) => `<th>${escapeHtml(h)}</th>`).join('')}</tr>
        </thead>
        <tbody>
          ${rows
            .map(
              (row) =>
                `<tr>${headers
                  .map((h) => `<td>${escapeHtml(row[h])}</td>`)
                  .join('')}</tr>`,
            )
            .join('')}
        </tbody>
      </table>`
    : '<p>No records found for this report.</p>';

  const win = window.open(
    '',
    '_blank',
    'noopener,noreferrer,width=1100,height=800',
  );

  if (!win) return;

  win.document.write(`<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>${escapeHtml(title)}</title>
<style>
@page {
  size: A4 landscape;
  margin: 12mm;
}

body {
  font-family: Arial, sans-serif;
  color: #111827;
  padding: 24px;
}

h1 {
  margin: 0 0 8px;
  font-size: 24px;
}

.meta {
  display: flex;
  gap: 18px;
  flex-wrap: wrap;
  color: #4b5563;
  font-size: 12px;
  margin-bottom: 18px;
}

table {
  border-collapse: collapse;
  width: 100%;
  font-size: 11px;
}

th,
td {
  border: 1px solid #d1d5db;
  padding: 7px;
  text-align: left;
}

th {
  background: #f3f4f6;
  font-weight: 700;
}

tbody tr:nth-child(even) {
  background: #fafafa;
}

.footer {
  margin-top: 18px;
  color: #6b7280;
  font-size: 10px;
}

@media print {
  button {
    display: none;
  }
}
</style>
</head>
<body>
<h1>${escapeHtml(title)}</h1>
<div class="meta">${metaHtml}</div>
${table}
<div class="footer">
Generated by ERPX-AI · ${escapeHtml(new Date().toLocaleString())}
</div>
<script>
window.onload = () => {
  window.print();
  setTimeout(() => window.close(), 300);
};
</script>
</body>
</html>`);

  win.document.close();
}

function triggerDownload(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement('a');

  anchor.href = url;
  anchor.download = filename;

  document.body.appendChild(anchor);
  anchor.click();
  anchor.remove();

  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

function escapeHtml(value: unknown) {
  return String(value ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}
